Repository DmitriyGovosyants/pet-support, pull requests merged in 2022-11, with the labels that each got.

#11 User page pets
  src/components/AddUsersPet/AddUsersPet.jsx
  src/components/AddUsersPet/AddUsersPet.styled.jsx
  src/components/PetItem/PetItem.jsx
  src/components/PetItem/PetItem.styled.jsx
  src/components/PetsData/PetsData.jsx
  src/components/PetsData/PetsData.styled.jsx
  src/components/PetsInterfaceButton/PetsInterfaceButton.jsx
  src/components/PetsInterfaceButton/PetsInterfaceButton.styled.jsx
  src/components/PetsList/PetsList.jsx
  src/components/PetsList/PetsList.styled.jsx
  src/components/index.js
  src/data/img/edit-icon.svg
  src/data/img/fluent_delete-16-filled.svg
  src/redux/petApi.js
  src/redux/store.js
Labels: question

#15 User page
  src/components/Container/Container.styled.js
  src/components/Logout/Logout.jsx
  src/components/Logout/Logout.styled.jsx
  src/components/UserData/UserData.jsx
  src/components/UserData/UserData.styled.jsx
  src/components/UserDataItem/UserDataItem.jsx
  src/components/UserDataItem/UserDataItem.styled.jsx
  src/data/img/team-img2-tab.jpg
  src/pages/UserPage/UserPage.jsx
  src/pages/UserPage/UserPage.styled.jsx
  src/router/PrivateRoute.js
Labels: question

#17 Future/notices page logic
  src/App.jsx
  src/components/AddNoticeButton/AddNoticeButton.jsx
  src/components/Nav/Nav.jsx
  src/components/NoticeCategoryItem/NoticeCategoryItem.jsx
  src/components/NoticesCategoriesList/NoticesCategoriesList.jsx
  src/components/NoticesCategoriesNav/NoticesCategoriesNav.jsx
  src/components/NoticesCategoriesNavButton/NoticesCategoriesNavButton.jsx
  src/components/NoticesCategoriesNavButton/NoticesCategoriesNavButton.styled.jsx
  src/constants/constants.js
  src/data/android-chrome-512x512.png
  src/data/img/dog.png
  src/hooks/useCategories.js
  src/hooks/useDate.js
  src/hooks/useRequest.js
  src/index.js
  src/pages/NoticesPage/NoticesPage.jsx
  src/redux/noticesApi.js
  src/router/routesPath.js
Labels: question

#12 ourfriends
  src/components/OurFriendItem/OurFriendItem.jsx
  src/components/OurFriendItem/OurFriendItem.styled.js
  src/components/OurFriendsList/OurFriendsList.jsx
  src/components/OurFriendsList/OurFriendsList.styled.js
  src/components/OurFriendsList/friends.json
  src/components/index.js
  src/data/img/partner.png
  src/pages/OurFriendsPage/OurFriendsPage.jsx
  src/pages/OurFriendsPage/OurFriendsPage.styled.jsx
  src/redux/friendsApi.js
  src/redux/store.js
  src/styles/theme.jsx
Labels: enhancement

#24 Addpetsmodal
  src/components/ModalAddsPet/ModalAddsPet.jsx
  src/components/ModalAddsPet/ModalAddsPets.styled.js
Labels: question

#43 Fix/routes user/pets
  src/components/AddUsersPet/AddUsersPet.jsx
  src/components/ModalAddsPet/ModalAddsPet.jsx
  src/components/ModalDelete/ModalDelete.jsx
  src/components/PetItem/PetItem.jsx
  src/components/PetItem/PetItem.styled.jsx
  src/components/PetsData/PetsData.jsx
  src/components/PetsData/PetsData.styled.jsx
  src/components/PetsList/PetsList.jsx
  src/data/img/no-image.webp
  src/redux/petApi.js
  src/redux/store.js
Labels: question

#46 Fix/home page
  src/components/SharedLayout/SharedLayout.jsx
  src/data/img/homePage/hp-bckg-circle-desktop@1x.png
  src/data/img/homePage/hp-bckg-circle-desktop@2x.png
  src/data/img/homePage/hp-bckg-desktop@1x.png
  src/data/img/homePage/hp-bckg-desktop@2x.png
  src/data/img/homePage/hp-bckg-heart-desktop@1x.png
  src/data/img/homePage/hp-bckg-heart-desktop@2x.png
  src/data/img/homePage/hp-bckg-left-desktop@1x.png
  src/data/img/homePage/hp-bckg-left-desktop@2x.png
  src/data/img/homePage/hp-bckg-mobile@1x.png
  src/data/img/homePage/hp-bckg-mobile@2x.png
  src/data/img/homePage/hp-bckg-right-desktop@1x.png
  src/data/img/homePage/hp-bckg-right-desktop@2x.png
  src/data/img/homePage/hp-bckg-tablet@1x.png
  src/data/img/homePage/hp-bckg-tablet@2x.png
  src/data/img/homePage/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.styled.js
Labels: help wanted

#27 general view and primary actions
  src/components/ModalNotice/ModalNotice.jsx
  src/components/ModalNotice/ModalNotice.styled.jsx
  src/components/NoticeCategoryItem/NoticeCategoryItem.jsx
Labels: question

#62 add deleting my-ads, photo in cards on error
  src/components/NoticeCategoryItem/NoticeCategoryItem.jsx
  src/components/NoticeCategoryItem/NoticeCategoryItem.styled.jsx
  src/components/NoticesCategoriesList/NoticesCategoriesList.jsx
  src/components/NoticesCategoriesList/NoticesCategoriesList.styled.jsx
  src/hooks/useFilter.js
  src/redux/noticesApi.js
Labels: question

#47 Update ModalAddsPet.jsx
  src/components/ModalAddsPet/ModalAddsPet.jsx
  src/components/ModalAddsPet/ModalAddsPets.styled.js
Labels: enhancement

#130 Feature/notice
  src/components/AddNoticeButton/AddNoticeButton.styled.js
  src/components/ModalDeleteNotice/ModalDeleteNotice.jsx
  src/components/ModalDeleteNotice/ModalDeleteNotice.styled.js
  src/components/NoticeCategoryItem/NoticeCategoryItem.jsx
  src/components/NoticesSearch/NoticesSearch.jsx
  src/components/index.js
  src/hooks/useFilter.js
Labels: question

#127 add feature cancel edit
  src/components/UserData/UserData.jsx
  src/components/UserData/UserData.styled.js
  src/components/UserDataItem/UserDataItem.jsx
Labels: question

#125 team
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.styled.js
  src/components/ModalTeam/ModalTeam.jsx
  src/components/ModalTeam/ModalTeam.styled.js
  src/components/NoticesCategoriesList/NoticesCategoriesList.jsx
  src/components/index.js
  src/data/img/LinkedIn.png
  src/data/json/team.json
Labels: question

#129 Fix/modal our friends
  .netlify/state.json
  src/components/ModalOurFriend/ModalOurFriend.jsx
  src/components/OurFriendItem/OurFriendItem.jsx
  src/components/index.js
Labels: question
